package tournament;

import java.util.*;

/** A small, platform-neutral JSON adapter around the recovered JVM methods. */
public final class Json {
  private final String text; private int at;
  private Json(String text) { this.text=text; }
  public static Object parse(String text) { Json p=new Json(text);Object value=p.value();p.space();if(p.at!=text.length())throw new IllegalArgumentException("Trailing JSON content");return value; }
  private void space(){while(at<text.length()&&Character.isWhitespace(text.charAt(at)))at++;}
  private Object value(){space();char c=text.charAt(at);if(c=='"')return string();if(c=='{'){at++;Map<String,Object> m=new LinkedHashMap<>();space();if(text.charAt(at)=='}'){at++;return m;}do{space();String k=string();space();if(text.charAt(at++)!=':')throw new IllegalArgumentException("Expected colon");m.put(k,value());space();char end=text.charAt(at++);if(end=='}')return m;if(end!=',')throw new IllegalArgumentException("Expected comma");}while(true);}if(c=='['){at++;List<Object> l=new ArrayList<>();space();if(text.charAt(at)==']'){at++;return l;}do{l.add(value());space();char end=text.charAt(at++);if(end==']')return l;if(end!=',')throw new IllegalArgumentException("Expected comma");}while(true);}if(text.startsWith("null",at)){at+=4;return null;}if(text.startsWith("true",at)){at+=4;return true;}if(text.startsWith("false",at)){at+=5;return false;}int start=at;while(at<text.length()&&"-+0123456789.eE".indexOf(text.charAt(at))>=0)at++;return Double.valueOf(text.substring(start,at));}
  private String string(){if(text.charAt(at++)!='"')throw new IllegalArgumentException("Expected string");StringBuilder b=new StringBuilder();while(at<text.length()){char c=text.charAt(at++);if(c=='"')return b.toString();if(c=='\\'){c=text.charAt(at++);switch(c){case 'n':c='\n';break;case 'r':c='\r';break;case 't':c='\t';break;case 'b':c='\b';break;case 'f':c='\f';break;case 'u':c=(char)Integer.parseInt(text.substring(at,at+4),16);at+=4;break;}}b.append(c);}throw new IllegalArgumentException("Unclosed string");}
  public static String write(Object value){if(value==null)return "null";if(value instanceof String||value instanceof Enum){String s=String.valueOf(value);StringBuilder b=new StringBuilder("\"");for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'||c=='\\')b.append('\\').append(c);else if(c=='\n')b.append("\\n");else if(c=='\r')b.append("\\r");else if(c=='\t')b.append("\\t");else b.append(c);}return b.append('"').toString();}if(value instanceof Map){StringBuilder b=new StringBuilder("{");boolean first=true;for(Object raw:((Map<?,?>)value).entrySet()){Map.Entry<?,?> e=(Map.Entry<?,?>)raw;if(!first)b.append(',');first=false;b.append(write(e.getKey())).append(':').append(write(e.getValue()));}return b.append('}').toString();}if(value instanceof Iterable){StringBuilder b=new StringBuilder("[");boolean first=true;for(Object item:(Iterable<?>)value){if(!first)b.append(',');first=false;b.append(write(item));}return b.append(']').toString();}return String.valueOf(value);}
}
