const allowedOrigins=new Set(['https://damidola.github.io','http://127.0.0.1:4173','http://localhost:4173']);
const idPattern=/^[a-f0-9]{48}$/;const secretPattern=/^[a-f0-9]{64}$/;
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const sha=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
function cleanPublic(input){
 if(!input||typeof input.name!=='string'||input.name.length>100||!Array.isArray(input.players)||input.players.length>256||!Array.isArray(input.rounds)||input.rounds.length>3000||!Array.isArray(input.standings)||input.standings.length>256)throw new Error('Некоректні дані турніру.');
 const players=input.players.map(p=>{if(typeof p.id!=='string'||p.id.length>100||typeof p.name!=='string'||p.name.length>100)throw new Error('Некоректний гравець.');return{id:p.id,name:p.name}});const ids=new Set(players.map(p=>p.id));
 const rounds=input.rounds.map((r,i)=>{if(r.number!==i+1||!Array.isArray(r.matches)||r.matches.length>128)throw new Error('Некоректний тур.');return{number:r.number,closed:!!r.closed,matches:r.matches.map(m=>{if(!ids.has(m.white)||m.black!==null&&!ids.has(m.black)||m.result!=null&&(typeof m.result!=='string'||m.result.length>20))throw new Error('Некоректна пара.');return{white:m.white,black:m.black,result:m.result||null,byePoints:Number(m.byePoints)||0}})}});
 const standings=input.standings.map(p=>{if(!ids.has(p.id)||!Number.isFinite(p.points)||!Number.isInteger(p.rank)||!Array.isArray(p.coefficients)||p.coefficients.length>7)throw new Error('Некоректна таблиця.');return{id:p.id,rank:p.rank,points:p.points,coefficients:p.coefficients.map(c=>({label:String(c.label).slice(0,30),value:Number(c.value)||0}))}});
 return{name:input.name,status:['draft','active','finished'].includes(input.status)?input.status:'active',plannedRounds:Number(input.plannedRounds)||0,order:String(input.order||'').slice(0,200),players,rounds,standings,updated:new Date().toISOString()};
}
export default{async fetch(request,env){
 const url=new URL(request.url),origin=request.headers.get('Origin');let response;
 try{
 if(request.method==='OPTIONS'){response=new Response(null,{status:204});}
 else if(url.pathname==='/api/health'){response=json({ok:true,storage:!!env.BUCKET});}
 else if(url.pathname.startsWith('/api/')){
 const match=url.pathname.match(/^\/api\/(public|backup)\/([a-f0-9]{48})$/);
 if(!match||!idPattern.test(match[2]))response=json({error:'Не знайдено.'},404);
 else if(!env.BUCKET)response=json({error:'Сховище ще недоступне.'},503);
 else{
 const [,kind,id]=match,key=kind+'/'+id,obj=await env.BUCKET.get(key),record=obj?await obj.json():null;
 const token=(request.headers.get('Authorization')||'').replace(/^Bearer /,'');
 const needsAuth=request.method!=='GET'||kind==='backup';
 let ownerHash;
 if(needsAuth){if(!secretPattern.test(token))return json({error:'Потрібен код доступу.'},401);ownerHash=await sha(token);if(record&&record.ownerHash!==ownerHash)return json({error:'Неправильний код доступу.'},403);if(origin&&!allowedOrigins.has(origin)&&origin!==url.origin)return json({error:'Недозволений сайт.'},403);}
 if(request.method==='GET')response=record?.data?json(record.data):json({error:'Турнір ще не опубліковано або публікацію вимкнено.'},404);
 else if(request.method==='PUT'){
 const max=kind==='backup'?4*1024*1024:1024*1024;if(Number(request.headers.get('Content-Length'))>max)return json({error:'Забагато даних.'},413);
 const text=await request.text();if(new TextEncoder().encode(text).length>max)return json({error:'Забагато даних.'},413);
 const input=JSON.parse(text),data=kind==='public'?cleanPublic(input):input;
 if(kind==='backup'&&(!data||data.version!==2||!Array.isArray(data.tournaments)||!Array.isArray(data.localPlayers)))throw new Error('Некоректна резервна копія.');
 const put=await env.BUCKET.put(key,JSON.stringify({ownerHash,data}),{onlyIf:obj?{etagMatches:obj.etag}:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});
 response=put?json({ok:true,updated:new Date().toISOString()}):json({error:'Дані оновлюються. Спробуйте ще раз.'},409);
 }else if(request.method==='DELETE'){
 if(!record)response=json({ok:true});else{await env.BUCKET.put(key,JSON.stringify({ownerHash,data:null}));response=json({ok:true});}
 }else response=json({error:'Метод не підтримується.'},405);
 }
 }else response=new Response(viewer,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none';"}});
 }catch(error){response=json({error:error instanceof SyntaxError?'Некоректний файл.':error.message||'Не вдалося оновити дані.'},400);}
 const headers=new Headers(response.headers);if(origin&&(allowedOrigins.has(origin)||origin===url.origin)){headers.set('Access-Control-Allow-Origin',origin);headers.set('Access-Control-Allow-Methods','GET, PUT, DELETE, OPTIONS');headers.set('Access-Control-Allow-Headers','Content-Type, Authorization');headers.set('Vary','Origin');}headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','no-referrer');return new Response(response.body,{status:response.status,headers});
}};
const viewer=String.raw`<!doctype html><html lang="uk"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#31701f"><title>Жеребківка турніру</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f8f3;color:#19231b;font:16px system-ui,sans-serif}header{padding:20px 16px;background:#31701f;color:white}h1{font-size:22px;margin:0;overflow-wrap:anywhere}header p{font-size:12px;opacity:.85;margin:7px 0 0}main{max-width:760px;margin:auto;padding:14px}button{font:inherit;cursor:pointer;touch-action:manipulation;border:0;border-radius:22px;padding:10px 16px;min-height:44px;background:#e6ede1;color:#274b20}button.selected{background:#31701f;color:#fff}.tabs{display:flex;gap:8px;overflow-x:auto;margin-bottom:14px;scrollbar-width:none}.tabs button{flex-shrink:0}.pair{background:white;border:1px solid #dbe4d6;border-radius:18px;padding:12px;margin-bottom:10px}.board{font-size:12px;color:#426437;margin-bottom:9px}.names{display:grid;grid-template-columns:minmax(0,1fr) 70px minmax(0,1fr);align-items:center;gap:8px}.names strong{overflow-wrap:anywhere;font-size:16px}.names strong:last-child{text-align:right}.result{text-align:center;color:#31701f;font-weight:700}.bye{font-size:14px}.rank{display:flex;align-items:center;gap:12px}.rank>span:first-child{width:26px;text-align:center;color:#31701f;font-weight:700}.rank strong{flex:1}.rank small{display:block;font-size:11px;color:#64705f;margin-top:4px}.rank>b{font-size:19px}.status{font-size:13px;color:#617258;margin:10px 0 14px}.empty{padding:24px;line-height:1.5}.footer{font-size:12px;color:#6d7966;text-align:center;padding:16px}h2{font-size:18px;margin:12px 0}.refresh{font-size:13px;padding:8px 12px}a{color:#31701f}@media(prefers-color-scheme:dark){body{background:#08100b;color:#e4e9e1}.pair{background:#1c271d;border-color:#3b4736}button{background:#273126;color:#d0e3c7}.board,.result,.rank>span:first-child{color:#99c58a}.status,.rank small,.footer{color:#b1c2a8}}
</style><header><h1 id="title">Жеребківка турніру</h1><p id="updated">Поточні та попередні тури · без реєстрації</p></header><main><nav class="tabs"><button id="pairs" class="selected">Тури</button><button id="standings">Місця</button><button id="refresh" class="refresh">Оновити</button></nav><div id="rounds" class="tabs"></div><div id="content" aria-live="polite"><p class="empty">Відкрийте посилання турніру, яке надіслав організатор.</p></div><p class="footer">Оновлюється автоматично кожні 15 секунд</p></main><script>
const id=location.pathname.match(/^\/t\/([a-f0-9]{48})$/)?.[1],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(Number(n)||0);let data=null,selected=null,mode='pairs',busy=false;
function render(){if(!data)return;document.getElementById('title').textContent=data.name;document.title=data.name+' — жеребківка';document.getElementById('updated').textContent='Оновлено '+new Date(data.updated).toLocaleString('uk-UA',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});const names=new Map(data.players.map(p=>[p.id,p.name])),round=data.rounds.find(r=>r.number===selected)||data.rounds.at(-1),box=document.getElementById('content');document.getElementById('rounds').innerHTML=mode==='pairs'?data.rounds.map(r=>'<button data-round="'+r.number+'" class="'+(round?.number===r.number?'selected':'')+'">Тур '+r.number+'</button>').join(''):'';
if(mode==='standings'){box.innerHTML='<p class="status">'+esc(data.order)+'</p>'+data.standings.map(p=>'<article class="pair rank"><span>'+p.rank+'</span><strong>'+esc(names.get(p.id))+'<small>'+p.coefficients.map(c=>esc(c.label)+' '+fmt(c.value)).join(' · ')+'</small></strong><b>'+fmt(p.points)+'</b></article>').join('');return;}
if(!round){box.innerHTML='<p class="empty">Турнір готується. Жеребківка з’явиться після створення першого туру.</p>';return;}
box.innerHTML='<h2>Тур '+round.number+'</h2><p class="status">'+(round.closed?'Завершено':'Триває')+'</p>'+round.matches.map((m,i)=>m.black===null?'<article class="pair bye">Без пари: <strong>'+esc(names.get(m.white))+'</strong> · '+fmt(m.byePoints)+' очк.</article>':'<article class="pair"><div class="board">Стіл '+(i+1)+'</div><div class="names"><strong>'+esc(names.get(m.white))+'</strong><span class="result">'+esc(m.result||'—')+'</span><strong>'+esc(names.get(m.black))+'</strong></div></article>').join('');}
async function refresh(){if(!id||busy)return;busy=true;try{const response=await fetch('/api/public/'+id,{cache:'no-store'});if(!response.ok)throw new Error('Публікація поки недоступна. Спробуйте оновити сторінку.');data=await response.json();render();}catch(error){if(!data)document.getElementById('content').innerHTML='<p class="empty">'+esc(error.message)+'</p>';else document.getElementById('updated').textContent='Немає зв’язку · показано останнє оновлення';}finally{busy=false;}}
document.getElementById('rounds').onclick=e=>{const b=e.target.closest('[data-round]');if(b){selected=Number(b.dataset.round)===data.rounds.at(-1)?.number?null:Number(b.dataset.round);render()}};for(const key of ['pairs','standings'])document.getElementById(key).onclick=()=>{mode=key;document.getElementById('pairs').classList.toggle('selected',key==='pairs');document.getElementById('standings').classList.toggle('selected',key==='standings');render()};document.getElementById('refresh').onclick=refresh;setInterval(()=>{if(!document.hidden)refresh()},15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});refresh();
</script></html>`;
